# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QRCodeDemo' do

    pod 'ZBarSDK', '~> 1.3.1'
    pod 'libqrencode', '~> 3.4.2'

end

target 'QRCodeDemoTests' do

end

target 'QRCodeDemoUITests' do

end

